import type {
  LeadLocation,
  PlatformCommission,
  PlatformCommissionRule,
  PlatformLead,
  PlatformPackage,
  PlatformPayment,
  PlatformSubscription,
  TenantLocationPlan,
} from "@/lib/platform-crm-types";
import type { TenantFeatureKey } from "@/lib/tenant";
import { BIZERY_PRICING_PLANS, PRICING_PLANS } from "@/lib/platform-pricing";
import { allTenantFeatures } from "@/lib/tenant-modules";

const presenceModules: TenantFeatureKey[] = ["website", "onlineMenu", "reviews", "gallery"];
const bookingModules: TenantFeatureKey[] = [...presenceModules, "reservations", "tablePlanner", "favorites"];
const operationsModules = Object.entries(allTenantFeatures(true))
  .filter(([, enabled]) => enabled)
  .map(([key]) => key as TenantFeatureKey);

export const PLATFORM_PACKAGES: PlatformPackage[] = PRICING_PLANS.map((plan, index) => {
  const bizery = BIZERY_PRICING_PLANS.find((p) => p.slug === plan.slug);
  return {
    id: `pkg-${plan.slug}`,
    name: plan.marketing_name,
    slug: plan.slug,
    vertical: "both",
    adapted_name: bizery?.marketing_name !== plan.marketing_name ? bizery?.marketing_name : null,
    description: plan.description,
    price_monthly: plan.price_annual,
    price_yearly: plan.price_annual * 12,
    currency: "EUR",
    modules:
      plan.slug === "presenza"
        ? presenceModules
        : plan.slug === "prenotazioni"
          ? bookingModules
          : operationsModules,
    is_active: true,
    sort_order: index + 1,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  };
});

function primaryLocation(
  id: string,
  name: string,
  address: string | null,
  city: string | null,
  province: string | null,
  postal_code: string | null,
): LeadLocation {
  return { id, name, address, city, province, postal_code, country: "IT", is_primary: true };
}

export const PLATFORM_LEADS: PlatformLead[] = [
  {
    id: "1",
    business_name: "Osteria della Piazza",
    business_slug: null,
    business_vertical: "food",
    contact_name: "Marco Ferri",
    contact_email: "marco@osteriadellapiazza.it",
    contact_phone: "+39 347 1234567",
    address: "Via Roma 12",
    city: "Bologna",
    province: "BO",
    postal_code: "40121",
    country: "IT",
    billing_name: "Osteria della Piazza S.n.c.",
    billing_vat: "IT08765432109",
    billing_cf: "08765432109",
    billing_address: "Via Roma 12",
    billing_city: "Bologna",
    billing_province: "BO",
    billing_postal_code: "40121",
    billing_sdi: "XXXXXXX",
    billing_pec: "osteriapiazza@pec.it",
    status: "prospect",
    stage: "proposal",
    temperature: "hot",
    source: "form_web",
    notes: "Interessato al pacchetto Prenotazioni. Richiamarlo la prossima settimana.",
    locations: [
      primaryLocation("loc-1a", "Centro", "Via Roma 12", "Bologna", "BO", "40121"),
      { id: "loc-1b", name: "Fiera", address: "Via Stalingrado 71", city: "Bologna", province: "BO", postal_code: "40128", country: "IT", is_primary: false },
    ],
    demo_url: null,
    demo_pr_url: null,
    official_domain: "osteriadellapiazza.menuary.it",
    official_domain_active: false,
    tenant_id: null,
    converted_at: null,
    sales_owner_id: "sales-giulia",
    sales_owner_name: "Giulia Rinaldi",
    created_at: "2026-05-01T10:00:00Z",
    updated_at: "2026-05-10T15:30:00Z",
  },
  {
    id: "2",
    business_name: "BePork",
    business_slug: "bepork",
    business_vertical: "food",
    contact_name: "Luca Bianchi",
    contact_email: "luca@bepork.it",
    contact_phone: "+39 338 9876543",
    address: "Via Veneto 5",
    city: "Roma",
    province: "RM",
    postal_code: "00187",
    country: "IT",
    billing_name: "BePork S.r.l.",
    billing_vat: "IT12345678901",
    billing_cf: "12345678901",
    billing_address: "Via Veneto 5",
    billing_city: "Roma",
    billing_province: "RM",
    billing_postal_code: "00187",
    billing_sdi: "M5UXCR1",
    billing_pec: "bepork@pec.it",
    status: "active",
    stage: "tenant",
    temperature: "hot",
    source: "diretto",
    notes: null,
    locations: [primaryLocation("loc-2a", "Bari centro", "Via Veneto 5", "Roma", "RM", "00187")],
    demo_url: "https://demo.menuary.it/bepork-demo",
    demo_pr_url: null,
    official_domain: "bepork.it",
    official_domain_active: true,
    tenant_id: "bepork",
    converted_at: "2026-02-01T00:00:00Z",
    sales_owner_id: "sales-matteo",
    sales_owner_name: "Matteo Serra",
    created_at: "2026-01-15T09:00:00Z",
    updated_at: "2026-05-01T12:00:00Z",
  },
  {
    id: "3",
    business_name: "Pizzeria Napoli Verace",
    business_slug: null,
    business_vertical: "food",
    contact_name: "Anna Esposito",
    contact_email: "anna@napoliverace.it",
    contact_phone: "+39 081 5556789",
    address: "Corso Umberto 34",
    city: "Napoli",
    province: "NA",
    postal_code: "80138",
    country: "IT",
    billing_name: null,
    billing_vat: null,
    billing_cf: null,
    billing_address: null,
    billing_city: null,
    billing_province: null,
    billing_postal_code: null,
    billing_sdi: null,
    billing_pec: null,
    status: "lead",
    stage: "contacted",
    temperature: "warm",
    source: "evento",
    notes: "Conosciuta al Sigep 2026.",
    locations: [primaryLocation("loc-3a", "Sede unica", "Corso Umberto 34", "Napoli", "NA", "80138")],
    demo_url: null,
    demo_pr_url: null,
    official_domain: "napoliverace.menuary.it",
    official_domain_active: false,
    tenant_id: null,
    converted_at: null,
    sales_owner_id: "sales-giulia",
    sales_owner_name: "Giulia Rinaldi",
    created_at: "2026-05-12T14:00:00Z",
    updated_at: "2026-05-12T14:00:00Z",
  },
  {
    id: "4",
    business_name: "Studio Legale Bruni",
    business_slug: null,
    business_vertical: "services",
    contact_name: "Silvia Bruni",
    contact_email: "silvia@studiobrunilegal.it",
    contact_phone: "+39 02 8901234",
    address: "Via Torino 88",
    city: "Milano",
    province: "MI",
    postal_code: "20123",
    country: "IT",
    billing_name: null,
    billing_vat: null,
    billing_cf: null,
    billing_address: null,
    billing_city: null,
    billing_province: null,
    billing_postal_code: null,
    billing_sdi: null,
    billing_pec: null,
    status: "prospect",
    stage: "demo",
    temperature: "hot",
    source: "form_web",
    notes: "Vuole sito professionale con form appuntamenti. Trial in attesa.",
    locations: [primaryLocation("loc-4a", "Studio Milano", "Via Torino 88", "Milano", "MI", "20123")],
    demo_url: "https://demo.bizery.it/studio-legale-bruni",
    demo_pr_url: "https://github.com/PynkStudio/Menuary/pull/123",
    official_domain: "studiobrunilegal.bizery.it",
    official_domain_active: false,
    tenant_id: null,
    converted_at: null,
    sales_owner_id: "sales-matteo",
    sales_owner_name: "Matteo Serra",
    created_at: "2026-05-08T11:00:00Z",
    updated_at: "2026-05-13T09:15:00Z",
  },
  {
    id: "5",
    business_name: "Centro Benessere Aurea",
    business_slug: "aurea",
    business_vertical: "services",
    contact_name: "Chiara Galli",
    contact_email: "chiara@centroaurea.it",
    contact_phone: "+39 055 2233445",
    address: "Via dei Servi 21",
    city: "Firenze",
    province: "FI",
    postal_code: "50122",
    country: "IT",
    billing_name: "Aurea S.r.l.",
    billing_vat: "IT09876543210",
    billing_cf: "09876543210",
    billing_address: "Via dei Servi 21",
    billing_city: "Firenze",
    billing_province: "FI",
    billing_postal_code: "50122",
    billing_sdi: "A4C7F9B",
    billing_pec: "aurea@pec.it",
    status: "active",
    stage: "tenant",
    temperature: "hot",
    source: "form_web",
    notes: null,
    locations: [
      primaryLocation("loc-5a", "Firenze centro", "Via dei Servi 21", "Firenze", "FI", "50122"),
      { id: "loc-5b", name: "Empoli", address: "Via Roma 9", city: "Empoli", province: "FI", postal_code: "50053", country: "IT", is_primary: false },
      { id: "loc-5c", name: "Prato", address: "Via Magnolfi 4", city: "Prato", province: "PO", postal_code: "59100", country: "IT", is_primary: false },
    ],
    demo_url: "https://demo.bizery.it/aurea",
    demo_pr_url: null,
    official_domain: "centroaurea.it",
    official_domain_active: true,
    tenant_id: "aurea",
    converted_at: "2026-04-10T00:00:00Z",
    sales_owner_id: "sales-giulia",
    sales_owner_name: "Giulia Rinaldi",
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-05-10T08:00:00Z",
  },
  {
    id: "6",
    business_name: "Studio Legale Aranzulla",
    business_slug: "studioaranzulla",
    business_vertical: "services",
    contact_name: "Lara Aranzulla",
    contact_email: "info@studiolegalearanzulla.it",
    contact_phone: null,
    address: null,
    city: null,
    province: null,
    postal_code: null,
    country: "IT",
    billing_name: null,
    billing_vat: null,
    billing_cf: null,
    billing_address: null,
    billing_city: null,
    billing_province: null,
    billing_postal_code: null,
    billing_sdi: null,
    billing_pec: null,
    status: "lead",
    stage: "new",
    temperature: "warm",
    source: "diretto",
    notes: "Studio legale – sito inaccessibile (JS-rendered, dati da completare). Contatto: Avv. Lara Aranzulla. Demo in sviluppo su previewSlug 'studioaranzulla'. Verificare indirizzo, telefono e P.IVA prima dell'onboarding.",
    locations: [primaryLocation("loc-6a", "Studio principale", null, null, null, null)],
    demo_url: "https://demo.bizery.it/studioaranzulla",
    demo_pr_url: null,
    official_domain: "studiolegalearanzulla.it",
    official_domain_active: false,
    tenant_id: null,
    converted_at: null,
    sales_owner_id: null,
    sales_owner_name: null,
    created_at: "2026-05-19T10:00:00Z",
    updated_at: "2026-05-19T10:00:00Z",
  },
];

function locationPlan(location: LeadLocation, packageSlug: string, packageName: string, priceFactor: number): TenantLocationPlan {
  return { ...location, package_slug: packageSlug, package_name: packageName, price_factor: priceFactor };
}

export const PLATFORM_SUBSCRIPTIONS: PlatformSubscription[] = [
  {
    id: "sub-1",
    lead_id: "1",
    package_id: "pkg-prenotazioni",
    billing_cycle: "monthly",
    price_override: null,
    setup_amount: 390,
    first_payment_amount: 489,
    currency: "EUR",
    status: "trial",
    started_at: "2026-05-01",
    trial_ends_at: "2026-05-31",
    current_period_start: "2026-05-01",
    current_period_end: "2026-05-31",
    next_renewal_at: "2026-06-01",
    cancelled_at: null,
    notes: "Seconda sede calcolata al 50% del piano principale.",
    created_at: "2026-05-01T10:00:00Z",
    updated_at: "2026-05-01T10:00:00Z",
    lead: PLATFORM_LEADS[0],
    package: PLATFORM_PACKAGES[1],
    location_plans: PLATFORM_LEADS[0].locations.map((loc, index) =>
      locationPlan(loc, "prenotazioni", "Prenotazioni", index === 0 ? 1 : 0.5),
    ),
  },
  {
    id: "sub-2",
    lead_id: "2",
    package_id: "pkg-operativita",
    billing_cycle: "yearly",
    price_override: null,
    setup_amount: 690,
    first_payment_amount: 2028,
    currency: "EUR",
    status: "active",
    started_at: "2026-02-01",
    trial_ends_at: null,
    current_period_start: "2026-02-01",
    current_period_end: "2027-01-31",
    next_renewal_at: "2027-02-01",
    cancelled_at: null,
    notes: null,
    created_at: "2026-02-01T10:00:00Z",
    updated_at: "2026-02-01T10:00:00Z",
    lead: PLATFORM_LEADS[1],
    package: PLATFORM_PACKAGES[2],
    location_plans: PLATFORM_LEADS[1].locations.map((loc) => locationPlan(loc, "operativita", "Operatività", 1)),
  },
  {
    id: "sub-3",
    lead_id: "5",
    package_id: "pkg-operativita",
    billing_cycle: "monthly",
    price_override: null,
    setup_amount: 590,
    first_payment_amount: 808,
    currency: "EUR",
    status: "active",
    started_at: "2026-04-10",
    trial_ends_at: null,
    current_period_start: "2026-05-10",
    current_period_end: "2026-06-09",
    next_renewal_at: "2026-06-10",
    cancelled_at: null,
    notes: "Associazione disgiunta: sede principale Operatività, sedi secondarie Presenza al 50%.",
    created_at: "2026-04-10T10:00:00Z",
    updated_at: "2026-05-10T08:00:00Z",
    lead: PLATFORM_LEADS[4],
    package: PLATFORM_PACKAGES[2],
    location_plans: [
      locationPlan(PLATFORM_LEADS[4].locations[0], "operativita", "Operatività", 1),
      ...PLATFORM_LEADS[4].locations.slice(1).map((loc) => locationPlan(loc, "presenza", "Presenza", 0.5)),
    ],
  },
];

export const PLATFORM_PAYMENTS: PlatformPayment[] = [
  {
    id: "pay-1",
    subscription_id: "sub-1",
    lead_id: "1",
    amount: 148.5,
    currency: "EUR",
    status: "pending",
    payment_method: "bonifico",
    payment_date: null,
    due_date: "2026-06-01",
    invoice_number: null,
    notes: null,
    stripe_payment_link: null,
    billing_payload: null,
    created_at: "2026-05-01T10:00:00Z",
    updated_at: "2026-05-01T10:00:00Z",
  },
  {
    id: "pay-2",
    subscription_id: "sub-2",
    lead_id: "2",
    amount: 2028,
    currency: "EUR",
    status: "paid",
    payment_method: "bonifico",
    payment_date: "2026-02-05",
    due_date: "2026-02-01",
    invoice_number: "FT-2026-001",
    notes: null,
    stripe_payment_link: "https://buy.stripe.com/test_bepork",
    billing_payload: {
      plan: "Operatività",
      billing_cycle: "yearly",
      setup_amount: 690,
      recurring_amount: 2028,
    },
    created_at: "2026-02-01T10:00:00Z",
    updated_at: "2026-02-05T10:00:00Z",
  },
  {
    id: "pay-3",
    subscription_id: "sub-3",
    lead_id: "5",
    amount: 218,
    currency: "EUR",
    status: "pending",
    payment_method: "sepa",
    payment_date: null,
    due_date: "2026-05-01",
    invoice_number: "FT-2026-018",
    notes: "Scaduto oltre soglia mensile: tenant da disattivare automaticamente.",
    stripe_payment_link: null,
    billing_payload: {
      plan: "Operatività",
      billing_cycle: "monthly",
      setup_amount: 590,
      recurring_amount: 218,
    },
    created_at: "2026-05-01T10:00:00Z",
    updated_at: "2026-05-01T10:00:00Z",
  },
];

export function calculateSubscriptionTotal(sub: PlatformSubscription): number {
  if (!sub.package) return sub.price_override ?? 0;
  if (sub.price_override !== null) return sub.price_override;
  const base = sub.billing_cycle === "yearly" ? sub.package.price_yearly ?? sub.package.price_monthly * 12 : sub.package.price_monthly;
  const planFactor = sub.location_plans?.reduce((sum, loc) => sum + loc.price_factor, 0) ?? 1;
  return base * planFactor;
}

export const PLATFORM_COMMISSION_RULES: PlatformCommissionRule[] = [
  { role: "superadmin", label: "Super Admin", commission_rate: 0, applies_to_sales: false },
  { role: "admin", label: "Admin", commission_rate: 0, applies_to_sales: false },
  { role: "venditore", label: "Venditore", commission_rate: 30, applies_to_sales: true },
  { role: "amministrazione", label: "Amministrazione", commission_rate: 0, applies_to_sales: false },
  { role: "gestore", label: "Gestore", commission_rate: 0, applies_to_sales: false },
  { role: "lead_inserter", label: "Inserimento lead", commission_rate: 0, applies_to_sales: false },
];

export function calculateFirstPaymentBase(sub: PlatformSubscription): number {
  const recurring = calculateSubscriptionTotal(sub);
  const setup = sub.setup_amount ?? 0;
  return sub.billing_cycle === "monthly" ? setup + recurring : recurring;
}

export function calculateCommissionAmount(firstPaymentBase: number, commissionRate: number): number {
  return Math.round(firstPaymentBase * (commissionRate / 100) * 100) / 100;
}

export const PLATFORM_COMMISSIONS: PlatformCommission[] = PLATFORM_SUBSCRIPTIONS
  .filter((sub) => sub.lead?.tenant_id)
  .map((sub, index) => {
    const lead = sub.lead!;
    const rule = PLATFORM_COMMISSION_RULES.find((item) => item.role === "venditore")!;
    const payment = PLATFORM_PAYMENTS.find((item) => item.subscription_id === sub.id)!;
    const recurring = calculateSubscriptionTotal(sub);
    const firstPaymentBase = calculateFirstPaymentBase(sub);

    return {
      id: `comm-${index + 1}`,
      lead_id: lead.id,
      tenant_id: lead.tenant_id,
      subscription_id: sub.id,
      payment_id: payment.id,
      seller_id: lead.sales_owner_id ?? "sales-unassigned",
      seller_name: lead.sales_owner_name ?? "Venditore non assegnato",
      seller_role: "venditore",
      business_name: lead.business_name,
      package_name: sub.package?.name ?? "Piano personalizzato",
      billing_cycle: sub.billing_cycle,
      recurring_amount: recurring,
      setup_amount: sub.setup_amount ?? 0,
      first_payment_amount: firstPaymentBase,
      commission_rate: rule.commission_rate,
      commission_amount: calculateCommissionAmount(firstPaymentBase, rule.commission_rate),
      status: payment.status === "paid" ? "approved" : "pending",
      closed_at: lead.converted_at ?? sub.started_at,
      paid_at: null,
    };
  });
